---
- hosts: all
  become: no
  tasks:
    - name: Copy the join command to server location
      copy:
        src: join-command
        dest: /tmp/join-command.sh
        mode: '0777'
    - name: Join the node to cluster
      become: true
      become_method: sudo
      shell: /tmp/join-command.sh
  handlers:
    - name: docker status
      service: name=docker state=started