apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-ingress-master
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "master"
spec:
  rules:
    - host: kubernetes.example.com