apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: green-deploy
  name: green-deployment
  namespace: ingress-test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: green
  template:
    metadata:
      labels:
        run: green
    spec:
      volumes:
      - name: webdata
        emptyDir: {}
      initContainers:
      - name: web-content
        image: busybox
        volumeMounts:
        - name: webdata
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1>I am <font color=green>GREEN</font></h1>" > /webdata/index.html']
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: webdata
          mountPath: "/usr/share/nginx/html"

---
apiVersion: v1
kind: Service
metadata:
  name: green-svc
  namespace: ingress-test-2
spec:
  selector:
    run: green
  ports:
    - port: 80