apiVersion: v1
kind: Service              # 1
metadata:
  name: sa-frontend-service
  namespace: sentiment-analysis
spec:
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: sa-frontend       # 7